urls.py
from django.urls import path
from . import views

app_name = 'birds'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('birds/', views.birds, name='birds'),
    path('eggs/', views.eggs, name='eggs'),
    path('sell/', views.sell, name='sell'),
    path('exchange/', views.exchange, name='exchange'),
]

models.py
from django.db import models
from django.utils import timezone


class Player(models.Model):
    name = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    gold = models.FloatField(default=0)
    silver = models.FloatField(default=0)
    eggs = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def egg_price(self):
        return 0.0001 # gold

    def birds_amount(self, bird_t):
        bird = self.birds_set.filter(template=bird_t).first()
        amount = bird.amount if bird else 0
        return amount

    def get_bird(self, bird_t):
        bird = self.birds_set.filter(template=bird_t).first()
        if bird:
            return bird
        else:
            return Birds(template=bird_t, player=self, amount=0, last_egg=timezone.now())

    def get_birds_list(self):
        bt_list = BirdTemplate.objects.all().order_by('cost')
        birds_list = [self.get_bird(bt) for bt in bt_list]
        return birds_list

    def buy_birds(self, bt_id, amount):
        if amount < 1:
            return False
        bt = BirdTemplate.objects.get(id=bt_id)
        # handle silver
        total_cost = amount * bt.cost
        silver_new = self.silver - total_cost
        if silver_new < 0:
            print('Not enough money.')
            return False
        self.silver = silver_new
        self.save()
        # handle birds
        bird = self.birds_set.filter(template=bt).first()
        if bird:
            bird.amount += amount
            bird.save()
        else:
            self.birds_set.create(template=bt, amount=amount, 
                last_egg=timezone.now())
        return True

    def gather_eggs(self):
        counter = 0
        for bird in self.get_birds_list():
            counter += bird._gather_eggs()
        self.eggs += counter
        self.save()

    def sell_eggs(self):
        self.gold += self.eggs * self.egg_price()
        self.eggs = 0
        self.save()
        
    def exchange(self, gold):
        if self.gold < gold:
            return False
        silver = gold * 100
        silver *= 4 # +300% bonus
        self.gold -= gold
        self.silver += silver
        self.save()
        return True
        

class BirdTemplate(models.Model):
    name = models.CharField(max_length=20)
    fertility = models.PositiveIntegerField()
    cost = models.PositiveIntegerField()

    def __str__(self):
        return "%s, %s eggs/h, %s silver" % (self.name, self.fertility, self.cost)


class Birds(models.Model):
    template = models.ForeignKey(BirdTemplate, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField(default=0)
    last_egg = models.DateTimeField('time of last egg made')

    def __str__(self):
        return "%s, player: %s, amount: %s" % (self.template.name, self.player.name, self.amount)

    def period(self):
        seconds = 60*60/self.template.fertility
        return timezone.timedelta(seconds=seconds)

    def eggs_available(self, single=False):
        delta = timezone.now() - self.last_egg
        eggs_from_bird = int(delta / self.period())
        if single:
            return eggs_from_bird
        return eggs_from_bird * self.amount

    def _gather_eggs(self):
        eggs_from_bird = self.eggs_available(single=True)
        if eggs_from_bird == 0:
            return 0
        delta = self.period() * eggs_from_bird
        self.last_egg += delta
        self.save()
        return eggs_from_bird * self.amount

views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Player, BirdTemplate

# helper
def get_player(request):
    pid = request.session.get('player_id', None)
    if pid:
        return Player.objects.filter(id=pid).first()
    else:
        return None

def index(request):
    return render(request, 'birds/index.html', 
        {'player': get_player(request)})

def register(request):
    try:
        name = request.POST['name']
        password = request.POST['password']
        try:
            Player.objects.get(name=name)
            error = "Player with that nickname is already created."
            return render(request, 'birds/register.html', 
                {'error': error})
        except Player.DoesNotExist:
            player = Player(name=name, password=password)
            player.silver = 500.0
            player.save()
            return redirect('birds:index')
    except:
        return render(request, 'birds/register.html')

def login(request):
    try:
        name = request.POST['name']
        password = request.POST['password']
        try:
            player = Player.objects.get(name=name)
            if player.password != password:
                raise Player.DoesNotExist
            request.session['player_id'] = player.id
            return redirect('birds:index')
        except Player.DoesNotExist:
            error = "Wrong nickname or password."
            return render(request, 'birds/login.html', 
                {'error': error})
    except:
        return render(request, 'birds/login.html')

def logout(request):
    try:
        del request.session['player_id']
        request.session.flush()
    except KeyError:
        pass
    return redirect('birds:index')

def birds(request):
    player = get_player(request)
    if not Player:
        return redirect('birds:logout')
    if request.POST:
        bt_id = request.POST['template']
        amount = int(request.POST['amount'])
        player.buy_birds(bt_id, amount)
    birds_list = player.get_birds_list()
    return render(request, 'birds/birds.html',
        {'player': player, 'birds': birds_list})

def eggs(request):
    player = get_player(request)
    if not Player:
        return redirect('birds:logout')
    if request.POST:
        player.gather_eggs()
    birds_list = player.get_birds_list()
    eggs_list = [b.eggs_available() for b in birds_list]
    return render(request, 'birds/eggs.html', {
        'player': player,
        'birds_and_eggs': zip(birds_list, eggs_list)
        })

def sell(request):
    player = get_player(request)
    if not Player:
        return redirect('birds:logout')
    if request.POST:
        player.sell_eggs()
    return render(request, 'birds/sell.html', {
        'player': player, 
        'gold_available': player.eggs * player.egg_price(),
        })

def exchange(request):
    player = get_player(request)
    if not Player:
        return redirect('birds:logout')
    if request.POST:
        try:
            gold = float(request.POST["amount"])
            player.exchange(gold)
        except:
            pass
    return render(request, 'birds/exchange.html', {
        'player': player, 
        })

templates/birds/birds.html
<h1><a href="{% url 'birds:index' %}">Birds</a></h1>

{% if player %}
<h2>Hello, {{ player.name }}!</h2>
<div>Silver: {{ player.silver|floatformat:2 }}</div>
<div>Gold: {{ player.gold|floatformat:2 }}</div>
{% endif %}

{% for bird in birds %}
<div class="bird">
  <p><strong>{{ bird.template.name }}</strong></p>
  <ul>
    <li>Fertility: {{ bird.template.fertility }} eggs/hour</li>
    <li>Cost: {{ bird.template.cost }} silver</li>
    <li>You have: {{ bird.amount }}</li>
  </ul>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="template" value="{{bird.template.id}}" />
    <input type="number" value="1" name="amount" />
    <input type="submit" value="Buy" />
  </form>
</div>
{% endfor %}

templates/birds/eggs.html
<h1><a href="{% url 'birds:index' %}">Birds</a></h1>

{% if player %}
<h2>Hello, {{ player.name }}!</h2>
<div>Silver: {{ player.silver|floatformat:2 }}</div>
<div>Gold: {{ player.gold|floatformat:2 }}</div>
{% endif %}

<ul>
  {% for bird, eggs in birds_and_eggs %}
  <li>Your {{ bird.amount }} {{ bird.template.name }} birds layed: {{ eggs }} eggs.</li>
  {% endfor %}
</ul>

<form method="post">
  {% csrf_token %}
  <input type="submit" value="Gather!" />
</form>

<p>You have {{ player.eggs }} eggs.</p>

templates/birds/exchange.html
<h1><a href="{% url 'birds:index' %}">Birds</a></h1>

{% if player %}
<h2>Hello, {{ player.name }}!</h2>
<div>Silver: {{ player.silver|floatformat:2 }}</div>
<div>Gold: {{ player.gold|floatformat:2 }}</div>
{% endif %}

<p>1 gold = 100 silver + 300% bonus.</p>

<form method="post">
  {% csrf_token %}
  I wanna exchange my 
  <input type="number" step="0.01" min="0" name="amount" /> 
  gold. <br/>
  <input type="submit" value="Exchange!" />
</form>

templates/birds/index.html
<h1><a href="{% url 'birds:index' %}">Birds</a></h1>

{% if player %}
<h2>Hello, {{ player.name }}!</h2>
<div>Silver: {{ player.silver|floatformat:2 }}</div>
<div>Gold: {{ player.gold|floatformat:2 }}</div>
{% endif %}

<ul>
  {% if player %}
  <li><a href="{% url 'birds:birds' %}">Buy birds</a></li>
  <li><a href="{% url 'birds:eggs' %}">Gather eggs</a></li>
  <li><a href="{% url 'birds:sell' %}">Sell eggs</a></li>
  <li><a href="{% url 'birds:exchange' %}">Exchange</a></li>
  <li><a href="{% url 'birds:logout' %}">Logout</a></li>
  {% else %}
  <li><a href="{% url 'birds:register' %}">Register</a></li>
  <li><a href="{% url 'birds:login' %}">Login</a></li>
  {% endif %}
</ul>

templates/birds/login.html
<h1><a href="{% url 'birds:index' %}">Birds</a></h1>
<h2>Login:</h2>
<form method="post">
  {% csrf_token %}
  <p>Nickname: <input type="text" name="name" /></p>
  <p>Password: <input type="password" name="password" /></p>
  <input type="submit" value="Login" />
</form>

{% if error %}
<p>{{ error }}</p>
{% endif %}

templates/birds/register.html
<h1><a href="{% url 'birds:index' %}">Birds</a></h1>
<h2>New Player:</h2>
<form method="post">
  {% csrf_token %}
  <p>Nickname: <input type="text" name="name" /></p>
  <p>Password: <input type="password" name="password" /></p>
  <input type="submit" value="Create" />
</form>

{% if error %}
<p>{{ error }}</p>
{% endif %}

templates/birds/sell.html
<h1><a href="{% url 'birds:index' %}">Birds</a></h1>

{% if player %}
<h2>Hello, {{ player.name }}!</h2>
<div>Silver: {{ player.silver|floatformat:2 }}</div>
<div>Gold: {{ player.gold|floatformat:2 }}</div>
{% endif %}

<p>You have {{ player.eggs }} eggs, you'll get {{ gold_available|floatformat:4 }} gold for it.</p>

<form method="post">
  {% csrf_token %}
  <input type="submit" value="Sell!" />
</form>